# config/database.yml
# 適宜username,password,socket,databaseを先ほど設定したものに書き換えてください。

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: sampleuser
  password: password
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: Sample_development

test:
  <<: *default
  database: Sample_test

production:
  <<: *default
  database: Sample_production
  username: Sample
  password: <%= ENV['Sample_PASSWORD'] %>
